name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCLOUD_SERVICE_KEY }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/molecularwatch/molecularwatch-repo/molecularwatch:latest .
        docker push us-central1-docker.pkg.dev/molecularwatch/molecularwatch-repo/molecularwatch:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy molecularwatch-service \
          --image us-central1-docker.pkg.dev/molecularwatch/molecularwatch-repo/molecularwatch:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated